<?php


    define("MERCH_ID", "ba61abe4-33ad-4933-856b-87f33acd4876");
    define("MERCH_KEY", "GRWRNLOVGGRNCFYSMSTMMUXPSKOKPGCTQPDCTHMV");

    //TODO:STORE THIS KIND OF CONSTANT AT THE ENVIRONMENT ITSELF
?>